spring:
  datasource:
    url: jdbc:mysql://localhost:3306/magician?useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

server:
  tomcat:
    uri-encoding: UTF-8