spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/magician
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#logging:
#  level:
#    org:
#      springframework: DEBUG